### ISSUE TITLE
Container won't run if domain doesn't exist

### ISSUE THREAD

**Issue by drym3r** [genuinetools/reg#85]
When setting the registry with `-r`, if there's nothing in the domain you run, the container won't run. This is ok if you run the image as is, but if you want to use a reverse proxy like nginx it's a problem. This change is recent, in the verson v0.9.0 it did work.

PD: Thanks for your work! This UI is awesome.

**Comment by jstoja** [comment]
Hey @drym3r if I get it right you have the issue where when you run `reg-server -r my.privateregistry.com` with my.privateregistry.com not being reachable, the server doesn't start. right?

To me this is a normal usecase since the reg-server needs to be able to contact the registry to get images informations. Maybe I'm misunderstanding...

**Comment by jessfraz** [comment]
more details would help here for sure

**Comment by jessfraz** [comment]
but I agree if the domain does not exist it should fail so closing for now until we get more information
